#!/usr/bin/env node
/**
 * Feature Plan Codegen
 *
 * Reads `src/main/initializers/*.spec.ts`, computes per-phase dependency batches
 * via topological sort, and emits `src/main/generated/featurePlan.ts`.
 *
 * Replaces the runtime topo-sort that used to live in the 485-line
 * FeatureManager. At runtime, `featureRunner` simply walks the precomputed plan.
 *
 * Parsing strategy: the installed TypeScript 6.x compiler API reads declarative
 * name/phase/dependencies/required/description literals. Every array element
 * must be an object literal. Unsupported syntax and forward-phase dependencies
 * fail closed. `init`/`cleanup` bodies are not inspected or evaluated.
 *
 * Exposed as both:
 *   - A standalone function `generateFeaturePlan({ projectRoot, write })`
 *     for build scripts and tests.
 *   - An Rsbuild plugin via the default export, runnable in any Rsbuild
 *     pipeline so the generated file is always up to date with the specs.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import prettier from 'prettier';
import { parseSpecSource } from './featureSpecParser.js';

export { parseSpecSource };

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PHASES = ['security', 'critical', 'ui', 'deferred'];
const PHASE_RANK = { security: 0, critical: 1, ui: 2, deferred: 3 };

const HEADER = `/**
 * Auto-generated by \`scripts/featurePlanPlugin.js\`. DO NOT EDIT.
 *
 * The plugin reads \`src/main/initializers/*.spec.ts\`, runs a topological sort
 * keyed by \`dependencies\`, and emits a phase → dependency-batched plan that
 * \`featureRunner\` walks at startup.
 */
`;

/**
 * Topologically sort entries within a single phase, returning batches.
 * Same-phase and earlier-phase dependencies are allowed. Forward-phase
 * dependencies are rejected before batching. Throws on cycle detection.
 */
function batchByDependencies(entries, phase, knownNames) {
  const inPhase = entries.filter((e) => e.phase === phase);
  const inPhaseNames = new Set(inPhase.map((e) => e.name));

  // Cycle detection via DFS
  const visiting = new Set();
  const visited = new Set();
  const visit = (e) => {
    if (visited.has(e.name)) return;
    if (visiting.has(e.name)) {
      throw new Error(`[featurePlanPlugin] Circular dependency detected at '${e.name}'`);
    }
    visiting.add(e.name);
    for (const dep of e.dependencies || []) {
      const next = inPhase.find((x) => x.name === dep);
      if (next) visit(next);
      else if (!knownNames.has(dep)) {
        throw new Error(`[featurePlanPlugin] '${e.name}' depends on unknown feature '${dep}'`);
      }
    }
    visiting.delete(e.name);
    visited.add(e.name);
  };
  for (const e of inPhase) visit(e);

  // Greedy batch assignment: a feature lands in batch N once all in-phase deps
  // are in batches < N.
  const batches = [];
  const assigned = new Set();
  let remaining = [...inPhase];
  while (remaining.length) {
    const ready = remaining.filter((e) =>
      (e.dependencies || []).every((d) => !inPhaseNames.has(d) || assigned.has(d))
    );
    if (!ready.length) {
      throw new Error(
        `[featurePlanPlugin] Unresolvable dependencies in '${phase}': ${remaining.map((e) => e.name).join(', ')}`
      );
    }
    batches.push(ready);
    for (const e of ready) assigned.add(e.name);
    remaining = remaining.filter((e) => !assigned.has(e.name));
  }
  return batches;
}

async function emitPlan(specFiles, plan) {
  const importLines = specFiles.map(
    ({ exportName, importPath }) => `import { ${exportName} } from '${importPath}';`
  );
  const phaseLines = PHASES.map((phase) => {
    const batches = plan[phase] || [];
    const inner = batches
      .map((batch) => `[${batch.map((name) => `get('${name}')`).join(', ')}]`)
      .join(', ');
    return `  ${phase}: [${inner}]`;
  });
  const raw = [
    HEADER,
    `import type { FeatureSpec, FeaturePriority } from '../utils/lifecycle/featureConfigTypes.js';`,
    ...importLines,
    ``,
    `const ALL_SPECS: readonly FeatureSpec[] = [`,
    ...specFiles.map(({ exportName }) => `  ...${exportName},`),
    `];`,
    ``,
    `const byName = new Map<string, FeatureSpec>(ALL_SPECS.map((s) => [s.name, s]));`,
    `const get = (name: string): FeatureSpec => {`,
    `  const spec = byName.get(name);`,
    `  if (!spec) throw new Error(\`[FEATURE_PLAN] Missing spec for '\${name}'\`);`,
    `  return spec;`,
    `};`,
    ``,
    `export const FEATURE_PLAN: Readonly<Record<FeaturePriority, readonly (readonly FeatureSpec[])[]>> = {`,
    ...phaseLines.map((line) => `${line},`),
    `};`,
    ``,
  ].join('\n');
  return prettier.format(raw, {
    parser: 'typescript',
    printWidth: 100,
    singleQuote: true,
    semi: true,
    trailingComma: 'all',
  });
}

/**
 * Pure (no I/O) plan builder: parses every input spec source, validates
 * uniqueness, runs per-phase topological batching, and emits the final
 * `featurePlan.ts` source string. Used by `generateFeaturePlan` and exposed
 * directly so tests can feed inline spec sources without touching the disk.
 *
 * @param {Array<{ file: string, source: string }>} inputs
 * @returns {{ source: string, plan: Record<string, string[][]>, allEntries: object[] }}
 */
export async function buildPlanFromSources(inputs) {
  const specFiles = inputs.map(({ file, source }) => {
    const { exportName, entries } = parseSpecSource(source, file);
    const importPath = `../initializers/${file.replace(/\.ts$/, '.js')}`;
    return { file, exportName, importPath, entries };
  });

  const allEntries = specFiles.flatMap((s) => s.entries);
  const knownNames = new Set(allEntries.map((e) => e.name));
  const origins = new Map();
  for (const specFile of specFiles) {
    specFile.entries.forEach((entry, index) => {
      origins.set(entry.name, { file: specFile.file, index });
    });
  }

  // Verify uniqueness
  const seen = new Set();
  for (const e of allEntries) {
    if (seen.has(e.name)) {
      throw new Error(`[featurePlanPlugin] Duplicate feature name: '${e.name}'`);
    }
    seen.add(e.name);
  }

  assertNoForwardPhaseDependencies(allEntries, origins);

  const plan = {};
  for (const phase of PHASES) {
    plan[phase] = batchByDependencies(allEntries, phase, knownNames).map((batch) =>
      batch.map((e) => e.name)
    );
  }

  const source = await emitPlan(specFiles, plan);
  return { source, plan, allEntries };
}

function assertNoForwardPhaseDependencies(allEntries, origins) {
  const byName = new Map(allEntries.map((entry) => [entry.name, entry]));
  for (const entry of allEntries) {
    for (const depName of entry.dependencies || []) {
      const dependency = byName.get(depName);
      if (!dependency) continue;
      if (PHASE_RANK[dependency.phase] > PHASE_RANK[entry.phase]) {
        const origin = origins.get(entry.name);
        const location = origin
          ? `${origin.file}[${origin.index}].dependencies`
          : `${entry.name}.dependencies`;
        throw new Error(
          `[featurePlanPlugin] ${location}: '${entry.name}' (${entry.phase}) cannot depend on later-phase '${depName}' (${dependency.phase})`
        );
      }
    }
  }
}

/**
 * Public entry point. Idempotent: writes only if content changed.
 *
 * @param {object} options
 * @param {string} options.projectRoot — repository root
 * @param {boolean} [options.write=true] — when false, returns the generated source without writing
 * @returns {{ outputPath: string, source: string, changed: boolean }}
 */
export async function generateFeaturePlan({ projectRoot, write = true } = {}) {
  const root = projectRoot || path.join(__dirname, '..');
  const specsDir = path.join(root, 'src/main/initializers');
  const outputDir = path.join(root, 'src/main/generated');
  const outputPath = path.join(outputDir, 'featurePlan.ts');

  const inputs = fs
    .readdirSync(specsDir)
    .filter((f) => f.endsWith('.spec.ts'))
    .sort()
    .map((f) => ({
      file: f,
      source: fs.readFileSync(path.join(specsDir, f), 'utf-8'),
    }));

  // Build all output before any write so parse/plan errors cannot touch the file.
  const { source, plan, allEntries } = await buildPlanFromSources(inputs);

  let changed = true;
  if (fs.existsSync(outputPath)) {
    const prev = fs.readFileSync(outputPath, 'utf-8');
    changed = prev !== source;
  }
  if (write && changed) {
    fs.mkdirSync(outputDir, { recursive: true });
    const tempPath = `${outputPath}.${process.pid}.tmp`;
    try {
      fs.writeFileSync(tempPath, source);
      fs.renameSync(tempPath, outputPath);
    } catch (error) {
      try {
        fs.unlinkSync(tempPath);
      } catch {
        // temp file may be absent if the write itself failed
      }
      throw error;
    }
    console.log(
      `[featurePlanPlugin] Emitted ${path.relative(root, outputPath)} ` +
        `(${allEntries.length} features, ${PHASES.map((p) => `${p}=${plan[p].length}b`).join(', ')})`
    );
  } else if (write) {
    console.log(`[featurePlanPlugin] ${path.relative(root, outputPath)} up to date`);
  }
  return { outputPath, source, changed };
}

/**
 * Rsbuild plugin: regenerates the plan before each compilation (dev/watch + prod).
 */
export const featurePlanPlugin = ({ projectRoot } = {}) => ({
  name: 'feature-plan-codegen',
  setup(api) {
    const run = async () => {
      try {
        await generateFeaturePlan({ projectRoot });
      } catch (error) {
        // Rspack catches thrown errors during onBeforeBuild and surfaces them.
        console.error('[featurePlanPlugin]', error.message);
        throw error;
      }
    };
    api.onBeforeBuild(run);
    if (api.onBeforeStartDevServer) api.onBeforeStartDevServer(run);
  },
});

export default featurePlanPlugin;
